name: a_great_wine
description: AGReATWine Mobile App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  path_provider:
  flutter_icons: ^1.1.0
  scrollable_positioned_list:
  syncfusion_flutter_charts: ^21.1.38
  lazy_load_scrollview:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/allwines35.db
    - assets/mycellar.db
    - assets/locale/
    - assets/logo.png
